name: quill_quest
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.0
  provider: ^6.1.5
  http: ^1.4.0
  firebase_auth: ^5.5.3


  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/yazısız1.png"


flutter:
  assets:
    - assets/images/yazılı.png
    - assets/images/yazısız.png
  uses-material-design: true

